/*
 * generated by Xtext 2.14.0
 */
package internship.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ModaGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MODAElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.MODA");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMODAAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMODAKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSociotechnicalsystemKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSociotechnicalsystemAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSociotechnicalsystemSocioTechnicalSystemParserRuleCall_4_1_0 = (RuleCall)cSociotechnicalsystemAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDataKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDataAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cDataDataParserRuleCall_5_2_0 = (RuleCall)cDataAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDataAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_5_3_1_0 = (RuleCall)cDataAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSoftwareKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSoftwareAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cSoftwareSoftwareParserRuleCall_6_1_0 = (RuleCall)cSoftwareAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cModelKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cModelAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cModelModelParserRuleCall_7_2_0 = (RuleCall)cModelAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cModelAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cModelModelParserRuleCall_7_3_1_0 = (RuleCall)cModelAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cModelroleKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cModelroleAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cModelroleModelRoleParserRuleCall_8_2_0 = (RuleCall)cModelroleAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cModelroleAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cModelroleModelRoleParserRuleCall_8_3_1_0 = (RuleCall)cModelroleAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//MODA:
		//	{MODA}
		//	'MODA'
		//	name=EString
		//	'{' ('sociotechnicalsystem' sociotechnicalsystem=SocioTechnicalSystem)? ('data' '{' data+=Data ("," data+=Data)* '}')?
		//	('software' software=Software)? ('model' '{' model+=Model ("," model+=Model)* '}')? ('modelrole' '{'
		//	modelrole+=ModelRole ("," modelrole+=ModelRole)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{MODA} 'MODA' name=EString '{' ('sociotechnicalsystem' sociotechnicalsystem=SocioTechnicalSystem)? ('data' '{'
		//data+=Data ("," data+=Data)* '}')? ('software' software=Software)? ('model' '{' model+=Model ("," model+=Model)* '}')?
		//('modelrole' '{' modelrole+=ModelRole ("," modelrole+=ModelRole)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{MODA}
		public Action getMODAAction_0() { return cMODAAction_0; }
		
		//'MODA'
		public Keyword getMODAKeyword_1() { return cMODAKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('sociotechnicalsystem' sociotechnicalsystem=SocioTechnicalSystem)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'sociotechnicalsystem'
		public Keyword getSociotechnicalsystemKeyword_4_0() { return cSociotechnicalsystemKeyword_4_0; }
		
		//sociotechnicalsystem=SocioTechnicalSystem
		public Assignment getSociotechnicalsystemAssignment_4_1() { return cSociotechnicalsystemAssignment_4_1; }
		
		//SocioTechnicalSystem
		public RuleCall getSociotechnicalsystemSocioTechnicalSystemParserRuleCall_4_1_0() { return cSociotechnicalsystemSocioTechnicalSystemParserRuleCall_4_1_0; }
		
		//('data' '{' data+=Data ("," data+=Data)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'data'
		public Keyword getDataKeyword_5_0() { return cDataKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//data+=Data
		public Assignment getDataAssignment_5_2() { return cDataAssignment_5_2; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_5_2_0() { return cDataDataParserRuleCall_5_2_0; }
		
		//("," data+=Data)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//data+=Data
		public Assignment getDataAssignment_5_3_1() { return cDataAssignment_5_3_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_5_3_1_0() { return cDataDataParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('software' software=Software)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'software'
		public Keyword getSoftwareKeyword_6_0() { return cSoftwareKeyword_6_0; }
		
		//software=Software
		public Assignment getSoftwareAssignment_6_1() { return cSoftwareAssignment_6_1; }
		
		//Software
		public RuleCall getSoftwareSoftwareParserRuleCall_6_1_0() { return cSoftwareSoftwareParserRuleCall_6_1_0; }
		
		//('model' '{' model+=Model ("," model+=Model)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'model'
		public Keyword getModelKeyword_7_0() { return cModelKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//model+=Model
		public Assignment getModelAssignment_7_2() { return cModelAssignment_7_2; }
		
		//Model
		public RuleCall getModelModelParserRuleCall_7_2_0() { return cModelModelParserRuleCall_7_2_0; }
		
		//("," model+=Model)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//model+=Model
		public Assignment getModelAssignment_7_3_1() { return cModelAssignment_7_3_1; }
		
		//Model
		public RuleCall getModelModelParserRuleCall_7_3_1_0() { return cModelModelParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('modelrole' '{' modelrole+=ModelRole ("," modelrole+=ModelRole)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'modelrole'
		public Keyword getModelroleKeyword_8_0() { return cModelroleKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//modelrole+=ModelRole
		public Assignment getModelroleAssignment_8_2() { return cModelroleAssignment_8_2; }
		
		//ModelRole
		public RuleCall getModelroleModelRoleParserRuleCall_8_2_0() { return cModelroleModelRoleParserRuleCall_8_2_0; }
		
		//("," modelrole+=ModelRole)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//modelrole+=ModelRole
		public Assignment getModelroleAssignment_8_3_1() { return cModelroleAssignment_8_3_1; }
		
		//ModelRole
		public RuleCall getModelroleModelRoleParserRuleCall_8_3_1_0() { return cModelroleModelRoleParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ModelRoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.ModelRole");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDescriptiveModelParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPredictiveModelParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPrescriptiveModelParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ModelRole:
		//	DescriptiveModel | PredictiveModel | PrescriptiveModel;
		@Override public ParserRule getRule() { return rule; }
		
		//DescriptiveModel | PredictiveModel | PrescriptiveModel
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DescriptiveModel
		public RuleCall getDescriptiveModelParserRuleCall_0() { return cDescriptiveModelParserRuleCall_0; }
		
		//PredictiveModel
		public RuleCall getPredictiveModelParserRuleCall_1() { return cPredictiveModelParserRuleCall_1; }
		
		//PrescriptiveModel
		public RuleCall getPrescriptiveModelParserRuleCall_2() { return cPrescriptiveModelParserRuleCall_2; }
	}
	public class SocioTechnicalSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.SocioTechnicalSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSocioTechnicalSystemAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSocioTechnicalSystemKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDataAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cDataDataCrossReference_4_2_0 = (CrossReference)cDataAssignment_4_2.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_4_2_0_1 = (RuleCall)cDataDataCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cDataAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cDataDataCrossReference_4_3_1_0 = (CrossReference)cDataAssignment_4_3_1.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cDataDataCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPrescriptivemodelKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPrescriptivemodelAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cPrescriptivemodelPrescriptiveModelCrossReference_5_1_0 = (CrossReference)cPrescriptivemodelAssignment_5_1.eContents().get(0);
		private final RuleCall cPrescriptivemodelPrescriptiveModelEStringParserRuleCall_5_1_0_1 = (RuleCall)cPrescriptivemodelPrescriptiveModelCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//SocioTechnicalSystem:
		//	{SocioTechnicalSystem}
		//	'SocioTechnicalSystem'
		//	name=EString
		//	'{' ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('prescriptivemodel'
		//	prescriptivemodel=[PrescriptiveModel|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SocioTechnicalSystem} 'SocioTechnicalSystem' name=EString '{' ('data' '(' data+=[Data|EString] (","
		//data+=[Data|EString])* ')')? ('prescriptivemodel' prescriptivemodel=[PrescriptiveModel|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{SocioTechnicalSystem}
		public Action getSocioTechnicalSystemAction_0() { return cSocioTechnicalSystemAction_0; }
		
		//'SocioTechnicalSystem'
		public Keyword getSocioTechnicalSystemKeyword_1() { return cSocioTechnicalSystemKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'data'
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_4_2() { return cDataAssignment_4_2; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_4_2_0() { return cDataDataCrossReference_4_2_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_4_2_0_1() { return cDataDataEStringParserRuleCall_4_2_0_1; }
		
		//("," data+=[Data|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_4_3_1() { return cDataAssignment_4_3_1; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_4_3_1_0() { return cDataDataCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_4_3_1_0_1() { return cDataDataEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('prescriptivemodel' prescriptivemodel=[PrescriptiveModel|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'prescriptivemodel'
		public Keyword getPrescriptivemodelKeyword_5_0() { return cPrescriptivemodelKeyword_5_0; }
		
		//prescriptivemodel=[PrescriptiveModel|EString]
		public Assignment getPrescriptivemodelAssignment_5_1() { return cPrescriptivemodelAssignment_5_1; }
		
		//[PrescriptiveModel|EString]
		public CrossReference getPrescriptivemodelPrescriptiveModelCrossReference_5_1_0() { return cPrescriptivemodelPrescriptiveModelCrossReference_5_1_0; }
		
		//EString
		public RuleCall getPrescriptivemodelPrescriptiveModelEStringParserRuleCall_5_1_0_1() { return cPrescriptivemodelPrescriptiveModelEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.Data");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDataAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDataKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDataTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDataTypeDataTypesEnumRuleCall_4_1_0 = (RuleCall)cDataTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSoftwareKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSoftwareAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cSoftwareSoftwareCrossReference_5_1_0 = (CrossReference)cSoftwareAssignment_5_1.eContents().get(0);
		private final RuleCall cSoftwareSoftwareEStringParserRuleCall_5_1_0_1 = (RuleCall)cSoftwareSoftwareCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSociotechnicalsystemKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSociotechnicalsystemAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cSociotechnicalsystemSocioTechnicalSystemCrossReference_6_1_0 = (CrossReference)cSociotechnicalsystemAssignment_6_1.eContents().get(0);
		private final RuleCall cSociotechnicalsystemSocioTechnicalSystemEStringParserRuleCall_6_1_0_1 = (RuleCall)cSociotechnicalsystemSocioTechnicalSystemCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cModelroleKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cModelroleAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cModelroleModelRoleCrossReference_7_1_0 = (CrossReference)cModelroleAssignment_7_1.eContents().get(0);
		private final RuleCall cModelroleModelRoleEStringParserRuleCall_7_1_0_1 = (RuleCall)cModelroleModelRoleCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Data:
		//	{Data}
		//	'Data'
		//	name=EString
		//	'{' ('dataType' dataType=DataTypes)? ('software' software=[Software|EString])? ('sociotechnicalsystem'
		//	sociotechnicalsystem=[SocioTechnicalSystem|EString])? ('modelrole' modelrole=[ModelRole|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Data} 'Data' name=EString '{' ('dataType' dataType=DataTypes)? ('software' software=[Software|EString])?
		//('sociotechnicalsystem' sociotechnicalsystem=[SocioTechnicalSystem|EString])? ('modelrole'
		//modelrole=[ModelRole|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Data}
		public Action getDataAction_0() { return cDataAction_0; }
		
		//'Data'
		public Keyword getDataKeyword_1() { return cDataKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('dataType' dataType=DataTypes)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'dataType'
		public Keyword getDataTypeKeyword_4_0() { return cDataTypeKeyword_4_0; }
		
		//dataType=DataTypes
		public Assignment getDataTypeAssignment_4_1() { return cDataTypeAssignment_4_1; }
		
		//DataTypes
		public RuleCall getDataTypeDataTypesEnumRuleCall_4_1_0() { return cDataTypeDataTypesEnumRuleCall_4_1_0; }
		
		//('software' software=[Software|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'software'
		public Keyword getSoftwareKeyword_5_0() { return cSoftwareKeyword_5_0; }
		
		//software=[Software|EString]
		public Assignment getSoftwareAssignment_5_1() { return cSoftwareAssignment_5_1; }
		
		//[Software|EString]
		public CrossReference getSoftwareSoftwareCrossReference_5_1_0() { return cSoftwareSoftwareCrossReference_5_1_0; }
		
		//EString
		public RuleCall getSoftwareSoftwareEStringParserRuleCall_5_1_0_1() { return cSoftwareSoftwareEStringParserRuleCall_5_1_0_1; }
		
		//('sociotechnicalsystem' sociotechnicalsystem=[SocioTechnicalSystem|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'sociotechnicalsystem'
		public Keyword getSociotechnicalsystemKeyword_6_0() { return cSociotechnicalsystemKeyword_6_0; }
		
		//sociotechnicalsystem=[SocioTechnicalSystem|EString]
		public Assignment getSociotechnicalsystemAssignment_6_1() { return cSociotechnicalsystemAssignment_6_1; }
		
		//[SocioTechnicalSystem|EString]
		public CrossReference getSociotechnicalsystemSocioTechnicalSystemCrossReference_6_1_0() { return cSociotechnicalsystemSocioTechnicalSystemCrossReference_6_1_0; }
		
		//EString
		public RuleCall getSociotechnicalsystemSocioTechnicalSystemEStringParserRuleCall_6_1_0_1() { return cSociotechnicalsystemSocioTechnicalSystemEStringParserRuleCall_6_1_0_1; }
		
		//('modelrole' modelrole=[ModelRole|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'modelrole'
		public Keyword getModelroleKeyword_7_0() { return cModelroleKeyword_7_0; }
		
		//modelrole=[ModelRole|EString]
		public Assignment getModelroleAssignment_7_1() { return cModelroleAssignment_7_1; }
		
		//[ModelRole|EString]
		public CrossReference getModelroleModelRoleCrossReference_7_1_0() { return cModelroleModelRoleCrossReference_7_1_0; }
		
		//EString
		public RuleCall getModelroleModelRoleEStringParserRuleCall_7_1_0_1() { return cModelroleModelRoleEStringParserRuleCall_7_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class SoftwareElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.Software");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSoftwareAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSoftwareKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStateEStringParserRuleCall_4_1_0 = (RuleCall)cStateAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDataKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDataAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cDataDataCrossReference_5_2_0 = (CrossReference)cDataAssignment_5_2.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_5_2_0_1 = (RuleCall)cDataDataCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDataAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cDataDataCrossReference_5_3_1_0 = (CrossReference)cDataAssignment_5_3_1.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cDataDataCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPrescriptivemodelKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPrescriptivemodelAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cPrescriptivemodelPrescriptiveModelCrossReference_6_1_0 = (CrossReference)cPrescriptivemodelAssignment_6_1.eContents().get(0);
		private final RuleCall cPrescriptivemodelPrescriptiveModelEStringParserRuleCall_6_1_0_1 = (RuleCall)cPrescriptivemodelPrescriptiveModelCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Software:
		//	{Software}
		//	'Software'
		//	name=EString
		//	'{' ('state' state=EString)? ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('prescriptivemodel'
		//	prescriptivemodel=[PrescriptiveModel|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Software} 'Software' name=EString '{' ('state' state=EString)? ('data' '(' data+=[Data|EString] (","
		//data+=[Data|EString])* ')')? ('prescriptivemodel' prescriptivemodel=[PrescriptiveModel|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Software}
		public Action getSoftwareAction_0() { return cSoftwareAction_0; }
		
		//'Software'
		public Keyword getSoftwareKeyword_1() { return cSoftwareKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('state' state=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'state'
		public Keyword getStateKeyword_4_0() { return cStateKeyword_4_0; }
		
		//state=EString
		public Assignment getStateAssignment_4_1() { return cStateAssignment_4_1; }
		
		//EString
		public RuleCall getStateEStringParserRuleCall_4_1_0() { return cStateEStringParserRuleCall_4_1_0; }
		
		//('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'data'
		public Keyword getDataKeyword_5_0() { return cDataKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_5_2() { return cDataAssignment_5_2; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_5_2_0() { return cDataDataCrossReference_5_2_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_5_2_0_1() { return cDataDataEStringParserRuleCall_5_2_0_1; }
		
		//("," data+=[Data|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_5_3_1() { return cDataAssignment_5_3_1; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_5_3_1_0() { return cDataDataCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_5_3_1_0_1() { return cDataDataEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('prescriptivemodel' prescriptivemodel=[PrescriptiveModel|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'prescriptivemodel'
		public Keyword getPrescriptivemodelKeyword_6_0() { return cPrescriptivemodelKeyword_6_0; }
		
		//prescriptivemodel=[PrescriptiveModel|EString]
		public Assignment getPrescriptivemodelAssignment_6_1() { return cPrescriptivemodelAssignment_6_1; }
		
		//[PrescriptiveModel|EString]
		public CrossReference getPrescriptivemodelPrescriptiveModelCrossReference_6_1_0() { return cPrescriptivemodelPrescriptiveModelCrossReference_6_1_0; }
		
		//EString
		public RuleCall getPrescriptivemodelPrescriptiveModelEStringParserRuleCall_6_1_0_1() { return cPrescriptivemodelPrescriptiveModelEStringParserRuleCall_6_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cModelroleKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cModelroleAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cModelroleModelRoleCrossReference_4_2_0 = (CrossReference)cModelroleAssignment_4_2.eContents().get(0);
		private final RuleCall cModelroleModelRoleEStringParserRuleCall_4_2_0_1 = (RuleCall)cModelroleModelRoleCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cModelroleAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cModelroleModelRoleCrossReference_4_3_1_0 = (CrossReference)cModelroleAssignment_4_3_1.eContents().get(0);
		private final RuleCall cModelroleModelRoleEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cModelroleModelRoleCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Model:
		//	{Model}
		//	'Model'
		//	name=EString
		//	'{' ('modelrole' '(' modelrole+=[ModelRole|EString] ("," modelrole+=[ModelRole|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Model} 'Model' name=EString '{' ('modelrole' '(' modelrole+=[ModelRole|EString] ("," modelrole+=[ModelRole|EString])*
		//')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }
		
		//'Model'
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('modelrole' '(' modelrole+=[ModelRole|EString] ("," modelrole+=[ModelRole|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'modelrole'
		public Keyword getModelroleKeyword_4_0() { return cModelroleKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//modelrole+=[ModelRole|EString]
		public Assignment getModelroleAssignment_4_2() { return cModelroleAssignment_4_2; }
		
		//[ModelRole|EString]
		public CrossReference getModelroleModelRoleCrossReference_4_2_0() { return cModelroleModelRoleCrossReference_4_2_0; }
		
		//EString
		public RuleCall getModelroleModelRoleEStringParserRuleCall_4_2_0_1() { return cModelroleModelRoleEStringParserRuleCall_4_2_0_1; }
		
		//("," modelrole+=[ModelRole|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//modelrole+=[ModelRole|EString]
		public Assignment getModelroleAssignment_4_3_1() { return cModelroleAssignment_4_3_1; }
		
		//[ModelRole|EString]
		public CrossReference getModelroleModelRoleCrossReference_4_3_1_0() { return cModelroleModelRoleCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getModelroleModelRoleEStringParserRuleCall_4_3_1_0_1() { return cModelroleModelRoleEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class PrescriptiveModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.PrescriptiveModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrescriptiveModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cModelKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cModelAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cModelModelCrossReference_4_0 = (CrossReference)cModelAssignment_4.eContents().get(0);
		private final RuleCall cModelModelEStringParserRuleCall_4_0_1 = (RuleCall)cModelModelCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDataKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDataAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cDataDataCrossReference_5_2_0 = (CrossReference)cDataAssignment_5_2.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_5_2_0_1 = (RuleCall)cDataDataCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDataAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cDataDataCrossReference_5_3_1_0 = (CrossReference)cDataAssignment_5_3_1.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cDataDataCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSoftwareKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cSoftwareAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cSoftwareSoftwareCrossReference_6_1_0 = (CrossReference)cSoftwareAssignment_6_1.eContents().get(0);
		private final RuleCall cSoftwareSoftwareEStringParserRuleCall_6_1_0_1 = (RuleCall)cSoftwareSoftwareCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSociotechnicalsystemKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSociotechnicalsystemAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cSociotechnicalsystemSocioTechnicalSystemCrossReference_7_1_0 = (CrossReference)cSociotechnicalsystemAssignment_7_1.eContents().get(0);
		private final RuleCall cSociotechnicalsystemSocioTechnicalSystemEStringParserRuleCall_7_1_0_1 = (RuleCall)cSociotechnicalsystemSocioTechnicalSystemCrossReference_7_1_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPredictivemodelKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cPredictivemodelAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final CrossReference cPredictivemodelPredictiveModelCrossReference_8_1_0 = (CrossReference)cPredictivemodelAssignment_8_1.eContents().get(0);
		private final RuleCall cPredictivemodelPredictiveModelEStringParserRuleCall_8_1_0_1 = (RuleCall)cPredictivemodelPredictiveModelCrossReference_8_1_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPrescriptivemodelKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cPrescriptivemodelAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cPrescriptivemodelPrescriptiveModelCrossReference_9_1_0 = (CrossReference)cPrescriptivemodelAssignment_9_1.eContents().get(0);
		private final RuleCall cPrescriptivemodelPrescriptiveModelEStringParserRuleCall_9_1_0_1 = (RuleCall)cPrescriptivemodelPrescriptiveModelCrossReference_9_1_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cPrescriptivemodeleOppositeKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cPrescriptivemodeleOppositeAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cPrescriptivemodeleOppositePrescriptiveModelCrossReference_10_1_0 = (CrossReference)cPrescriptivemodeleOppositeAssignment_10_1.eContents().get(0);
		private final RuleCall cPrescriptivemodeleOppositePrescriptiveModelEStringParserRuleCall_10_1_0_1 = (RuleCall)cPrescriptivemodeleOppositePrescriptiveModelCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//PrescriptiveModel:
		//	'PrescriptiveModel'
		//	name=EString
		//	'{'
		//	'model' model=[Model|EString] ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('software'
		//	software=[Software|EString])? ('sociotechnicalsystem' sociotechnicalsystem=[SocioTechnicalSystem|EString])?
		//	('predictivemodel' predictivemodel=[PredictiveModel|EString])? ('prescriptivemodel'
		//	prescriptivemodel=[PrescriptiveModel|EString])? ('prescriptivemodeleOpposite'
		//	prescriptivemodeleOpposite=[PrescriptiveModel|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'PrescriptiveModel' name=EString '{' 'model' model=[Model|EString] ('data' '(' data+=[Data|EString] (","
		//data+=[Data|EString])* ')')? ('software' software=[Software|EString])? ('sociotechnicalsystem'
		//sociotechnicalsystem=[SocioTechnicalSystem|EString])? ('predictivemodel' predictivemodel=[PredictiveModel|EString])?
		//('prescriptivemodel' prescriptivemodel=[PrescriptiveModel|EString])? ('prescriptivemodeleOpposite'
		//prescriptivemodeleOpposite=[PrescriptiveModel|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//'PrescriptiveModel'
		public Keyword getPrescriptiveModelKeyword_0() { return cPrescriptiveModelKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'model'
		public Keyword getModelKeyword_3() { return cModelKeyword_3; }
		
		//model=[Model|EString]
		public Assignment getModelAssignment_4() { return cModelAssignment_4; }
		
		//[Model|EString]
		public CrossReference getModelModelCrossReference_4_0() { return cModelModelCrossReference_4_0; }
		
		//EString
		public RuleCall getModelModelEStringParserRuleCall_4_0_1() { return cModelModelEStringParserRuleCall_4_0_1; }
		
		//('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'data'
		public Keyword getDataKeyword_5_0() { return cDataKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_5_2() { return cDataAssignment_5_2; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_5_2_0() { return cDataDataCrossReference_5_2_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_5_2_0_1() { return cDataDataEStringParserRuleCall_5_2_0_1; }
		
		//("," data+=[Data|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_5_3_1() { return cDataAssignment_5_3_1; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_5_3_1_0() { return cDataDataCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_5_3_1_0_1() { return cDataDataEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('software' software=[Software|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'software'
		public Keyword getSoftwareKeyword_6_0() { return cSoftwareKeyword_6_0; }
		
		//software=[Software|EString]
		public Assignment getSoftwareAssignment_6_1() { return cSoftwareAssignment_6_1; }
		
		//[Software|EString]
		public CrossReference getSoftwareSoftwareCrossReference_6_1_0() { return cSoftwareSoftwareCrossReference_6_1_0; }
		
		//EString
		public RuleCall getSoftwareSoftwareEStringParserRuleCall_6_1_0_1() { return cSoftwareSoftwareEStringParserRuleCall_6_1_0_1; }
		
		//('sociotechnicalsystem' sociotechnicalsystem=[SocioTechnicalSystem|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'sociotechnicalsystem'
		public Keyword getSociotechnicalsystemKeyword_7_0() { return cSociotechnicalsystemKeyword_7_0; }
		
		//sociotechnicalsystem=[SocioTechnicalSystem|EString]
		public Assignment getSociotechnicalsystemAssignment_7_1() { return cSociotechnicalsystemAssignment_7_1; }
		
		//[SocioTechnicalSystem|EString]
		public CrossReference getSociotechnicalsystemSocioTechnicalSystemCrossReference_7_1_0() { return cSociotechnicalsystemSocioTechnicalSystemCrossReference_7_1_0; }
		
		//EString
		public RuleCall getSociotechnicalsystemSocioTechnicalSystemEStringParserRuleCall_7_1_0_1() { return cSociotechnicalsystemSocioTechnicalSystemEStringParserRuleCall_7_1_0_1; }
		
		//('predictivemodel' predictivemodel=[PredictiveModel|EString])?
		public Group getGroup_8() { return cGroup_8; }
		
		//'predictivemodel'
		public Keyword getPredictivemodelKeyword_8_0() { return cPredictivemodelKeyword_8_0; }
		
		//predictivemodel=[PredictiveModel|EString]
		public Assignment getPredictivemodelAssignment_8_1() { return cPredictivemodelAssignment_8_1; }
		
		//[PredictiveModel|EString]
		public CrossReference getPredictivemodelPredictiveModelCrossReference_8_1_0() { return cPredictivemodelPredictiveModelCrossReference_8_1_0; }
		
		//EString
		public RuleCall getPredictivemodelPredictiveModelEStringParserRuleCall_8_1_0_1() { return cPredictivemodelPredictiveModelEStringParserRuleCall_8_1_0_1; }
		
		//('prescriptivemodel' prescriptivemodel=[PrescriptiveModel|EString])?
		public Group getGroup_9() { return cGroup_9; }
		
		//'prescriptivemodel'
		public Keyword getPrescriptivemodelKeyword_9_0() { return cPrescriptivemodelKeyword_9_0; }
		
		//prescriptivemodel=[PrescriptiveModel|EString]
		public Assignment getPrescriptivemodelAssignment_9_1() { return cPrescriptivemodelAssignment_9_1; }
		
		//[PrescriptiveModel|EString]
		public CrossReference getPrescriptivemodelPrescriptiveModelCrossReference_9_1_0() { return cPrescriptivemodelPrescriptiveModelCrossReference_9_1_0; }
		
		//EString
		public RuleCall getPrescriptivemodelPrescriptiveModelEStringParserRuleCall_9_1_0_1() { return cPrescriptivemodelPrescriptiveModelEStringParserRuleCall_9_1_0_1; }
		
		//('prescriptivemodeleOpposite' prescriptivemodeleOpposite=[PrescriptiveModel|EString])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'prescriptivemodeleOpposite'
		public Keyword getPrescriptivemodeleOppositeKeyword_10_0() { return cPrescriptivemodeleOppositeKeyword_10_0; }
		
		//prescriptivemodeleOpposite=[PrescriptiveModel|EString]
		public Assignment getPrescriptivemodeleOppositeAssignment_10_1() { return cPrescriptivemodeleOppositeAssignment_10_1; }
		
		//[PrescriptiveModel|EString]
		public CrossReference getPrescriptivemodeleOppositePrescriptiveModelCrossReference_10_1_0() { return cPrescriptivemodeleOppositePrescriptiveModelCrossReference_10_1_0; }
		
		//EString
		public RuleCall getPrescriptivemodeleOppositePrescriptiveModelEStringParserRuleCall_10_1_0_1() { return cPrescriptivemodeleOppositePrescriptiveModelEStringParserRuleCall_10_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class PredictiveModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.PredictiveModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPredictiveModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cModelKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cModelAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cModelModelCrossReference_4_0 = (CrossReference)cModelAssignment_4.eContents().get(0);
		private final RuleCall cModelModelEStringParserRuleCall_4_0_1 = (RuleCall)cModelModelCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDataKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDataAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cDataDataCrossReference_5_2_0 = (CrossReference)cDataAssignment_5_2.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_5_2_0_1 = (RuleCall)cDataDataCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDataAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cDataDataCrossReference_5_3_1_0 = (CrossReference)cDataAssignment_5_3_1.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cDataDataCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPrescriptivemodelKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPrescriptivemodelAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cPrescriptivemodelPrescriptiveModelCrossReference_6_1_0 = (CrossReference)cPrescriptivemodelAssignment_6_1.eContents().get(0);
		private final RuleCall cPrescriptivemodelPrescriptiveModelEStringParserRuleCall_6_1_0_1 = (RuleCall)cPrescriptivemodelPrescriptiveModelCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cDescriptivemodelKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cDescriptivemodelAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cDescriptivemodelDescriptiveModelCrossReference_7_1_0 = (CrossReference)cDescriptivemodelAssignment_7_1.eContents().get(0);
		private final RuleCall cDescriptivemodelDescriptiveModelEStringParserRuleCall_7_1_0_1 = (RuleCall)cDescriptivemodelDescriptiveModelCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//PredictiveModel:
		//	'PredictiveModel'
		//	name=EString
		//	'{'
		//	'model' model=[Model|EString] ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('prescriptivemodel'
		//	prescriptivemodel=[PrescriptiveModel|EString])? ('descriptivemodel' descriptivemodel=[DescriptiveModel|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'PredictiveModel' name=EString '{' 'model' model=[Model|EString] ('data' '(' data+=[Data|EString] (","
		//data+=[Data|EString])* ')')? ('prescriptivemodel' prescriptivemodel=[PrescriptiveModel|EString])? ('descriptivemodel'
		//descriptivemodel=[DescriptiveModel|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//'PredictiveModel'
		public Keyword getPredictiveModelKeyword_0() { return cPredictiveModelKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'model'
		public Keyword getModelKeyword_3() { return cModelKeyword_3; }
		
		//model=[Model|EString]
		public Assignment getModelAssignment_4() { return cModelAssignment_4; }
		
		//[Model|EString]
		public CrossReference getModelModelCrossReference_4_0() { return cModelModelCrossReference_4_0; }
		
		//EString
		public RuleCall getModelModelEStringParserRuleCall_4_0_1() { return cModelModelEStringParserRuleCall_4_0_1; }
		
		//('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'data'
		public Keyword getDataKeyword_5_0() { return cDataKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_5_2() { return cDataAssignment_5_2; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_5_2_0() { return cDataDataCrossReference_5_2_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_5_2_0_1() { return cDataDataEStringParserRuleCall_5_2_0_1; }
		
		//("," data+=[Data|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_5_3_1() { return cDataAssignment_5_3_1; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_5_3_1_0() { return cDataDataCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_5_3_1_0_1() { return cDataDataEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('prescriptivemodel' prescriptivemodel=[PrescriptiveModel|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'prescriptivemodel'
		public Keyword getPrescriptivemodelKeyword_6_0() { return cPrescriptivemodelKeyword_6_0; }
		
		//prescriptivemodel=[PrescriptiveModel|EString]
		public Assignment getPrescriptivemodelAssignment_6_1() { return cPrescriptivemodelAssignment_6_1; }
		
		//[PrescriptiveModel|EString]
		public CrossReference getPrescriptivemodelPrescriptiveModelCrossReference_6_1_0() { return cPrescriptivemodelPrescriptiveModelCrossReference_6_1_0; }
		
		//EString
		public RuleCall getPrescriptivemodelPrescriptiveModelEStringParserRuleCall_6_1_0_1() { return cPrescriptivemodelPrescriptiveModelEStringParserRuleCall_6_1_0_1; }
		
		//('descriptivemodel' descriptivemodel=[DescriptiveModel|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'descriptivemodel'
		public Keyword getDescriptivemodelKeyword_7_0() { return cDescriptivemodelKeyword_7_0; }
		
		//descriptivemodel=[DescriptiveModel|EString]
		public Assignment getDescriptivemodelAssignment_7_1() { return cDescriptivemodelAssignment_7_1; }
		
		//[DescriptiveModel|EString]
		public CrossReference getDescriptivemodelDescriptiveModelCrossReference_7_1_0() { return cDescriptivemodelDescriptiveModelCrossReference_7_1_0; }
		
		//EString
		public RuleCall getDescriptivemodelDescriptiveModelEStringParserRuleCall_7_1_0_1() { return cDescriptivemodelDescriptiveModelEStringParserRuleCall_7_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class DescriptiveModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.DescriptiveModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDescriptiveModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cModelKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cModelAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cModelModelCrossReference_4_0 = (CrossReference)cModelAssignment_4.eContents().get(0);
		private final RuleCall cModelModelEStringParserRuleCall_4_0_1 = (RuleCall)cModelModelCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDataKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDataAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cDataDataCrossReference_5_2_0 = (CrossReference)cDataAssignment_5_2.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_5_2_0_1 = (RuleCall)cDataDataCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cDataAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cDataDataCrossReference_5_3_1_0 = (CrossReference)cDataAssignment_5_3_1.eContents().get(0);
		private final RuleCall cDataDataEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cDataDataCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPredictivemodelKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPredictivemodelAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cPredictivemodelPredictiveModelCrossReference_6_1_0 = (CrossReference)cPredictivemodelAssignment_6_1.eContents().get(0);
		private final RuleCall cPredictivemodelPredictiveModelEStringParserRuleCall_6_1_0_1 = (RuleCall)cPredictivemodelPredictiveModelCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//DescriptiveModel:
		//	'DescriptiveModel'
		//	name=EString
		//	'{'
		//	'model' model=[Model|EString] ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('predictivemodel'
		//	predictivemodel=[PredictiveModel|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'DescriptiveModel' name=EString '{' 'model' model=[Model|EString] ('data' '(' data+=[Data|EString] (","
		//data+=[Data|EString])* ')')? ('predictivemodel' predictivemodel=[PredictiveModel|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//'DescriptiveModel'
		public Keyword getDescriptiveModelKeyword_0() { return cDescriptiveModelKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'model'
		public Keyword getModelKeyword_3() { return cModelKeyword_3; }
		
		//model=[Model|EString]
		public Assignment getModelAssignment_4() { return cModelAssignment_4; }
		
		//[Model|EString]
		public CrossReference getModelModelCrossReference_4_0() { return cModelModelCrossReference_4_0; }
		
		//EString
		public RuleCall getModelModelEStringParserRuleCall_4_0_1() { return cModelModelEStringParserRuleCall_4_0_1; }
		
		//('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'data'
		public Keyword getDataKeyword_5_0() { return cDataKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_5_2() { return cDataAssignment_5_2; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_5_2_0() { return cDataDataCrossReference_5_2_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_5_2_0_1() { return cDataDataEStringParserRuleCall_5_2_0_1; }
		
		//("," data+=[Data|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//data+=[Data|EString]
		public Assignment getDataAssignment_5_3_1() { return cDataAssignment_5_3_1; }
		
		//[Data|EString]
		public CrossReference getDataDataCrossReference_5_3_1_0() { return cDataDataCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getDataDataEStringParserRuleCall_5_3_1_0_1() { return cDataDataEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('predictivemodel' predictivemodel=[PredictiveModel|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'predictivemodel'
		public Keyword getPredictivemodelKeyword_6_0() { return cPredictivemodelKeyword_6_0; }
		
		//predictivemodel=[PredictiveModel|EString]
		public Assignment getPredictivemodelAssignment_6_1() { return cPredictivemodelAssignment_6_1; }
		
		//[PredictiveModel|EString]
		public CrossReference getPredictivemodelPredictiveModelCrossReference_6_1_0() { return cPredictivemodelPredictiveModelCrossReference_6_1_0; }
		
		//EString
		public RuleCall getPredictivemodelPredictiveModelEStringParserRuleCall_6_1_0_1() { return cPredictivemodelPredictiveModelEStringParserRuleCall_6_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	public class DataTypesElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "internship.Moda.DataTypes");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cInputDataEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cInputDataInputDataKeyword_0_0 = (Keyword)cInputDataEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOutputDataEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOutputDataOutputDataKeyword_1_0 = (Keyword)cOutputDataEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cExternalDataEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cExternalDataExternalDataKeyword_2_0 = (Keyword)cExternalDataEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMeasuredDataEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMeasuredDataMeasuredDataKeyword_3_0 = (Keyword)cMeasuredDataEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum DataTypes:
		//	InputData | OutputData | ExternalData | MeasuredData;
		public EnumRule getRule() { return rule; }
		
		//InputData | OutputData | ExternalData | MeasuredData
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//InputData
		public EnumLiteralDeclaration getInputDataEnumLiteralDeclaration_0() { return cInputDataEnumLiteralDeclaration_0; }
		
		//'InputData'
		public Keyword getInputDataInputDataKeyword_0_0() { return cInputDataInputDataKeyword_0_0; }
		
		//OutputData
		public EnumLiteralDeclaration getOutputDataEnumLiteralDeclaration_1() { return cOutputDataEnumLiteralDeclaration_1; }
		
		//'OutputData'
		public Keyword getOutputDataOutputDataKeyword_1_0() { return cOutputDataOutputDataKeyword_1_0; }
		
		//ExternalData
		public EnumLiteralDeclaration getExternalDataEnumLiteralDeclaration_2() { return cExternalDataEnumLiteralDeclaration_2; }
		
		//'ExternalData'
		public Keyword getExternalDataExternalDataKeyword_2_0() { return cExternalDataExternalDataKeyword_2_0; }
		
		//MeasuredData
		public EnumLiteralDeclaration getMeasuredDataEnumLiteralDeclaration_3() { return cMeasuredDataEnumLiteralDeclaration_3; }
		
		//'MeasuredData'
		public Keyword getMeasuredDataMeasuredDataKeyword_3_0() { return cMeasuredDataMeasuredDataKeyword_3_0; }
	}
	
	private final MODAElements pMODA;
	private final ModelRoleElements pModelRole;
	private final SocioTechnicalSystemElements pSocioTechnicalSystem;
	private final DataElements pData;
	private final SoftwareElements pSoftware;
	private final EStringElements pEString;
	private final ModelElements pModel;
	private final PrescriptiveModelElements pPrescriptiveModel;
	private final PredictiveModelElements pPredictiveModel;
	private final DescriptiveModelElements pDescriptiveModel;
	private final DataTypesElements eDataTypes;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ModaGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMODA = new MODAElements();
		this.pModelRole = new ModelRoleElements();
		this.pSocioTechnicalSystem = new SocioTechnicalSystemElements();
		this.pData = new DataElements();
		this.pSoftware = new SoftwareElements();
		this.pEString = new EStringElements();
		this.pModel = new ModelElements();
		this.pPrescriptiveModel = new PrescriptiveModelElements();
		this.pPredictiveModel = new PredictiveModelElements();
		this.pDescriptiveModel = new DescriptiveModelElements();
		this.eDataTypes = new DataTypesElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("internship.Moda".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MODA:
	//	{MODA}
	//	'MODA'
	//	name=EString
	//	'{' ('sociotechnicalsystem' sociotechnicalsystem=SocioTechnicalSystem)? ('data' '{' data+=Data ("," data+=Data)* '}')?
	//	('software' software=Software)? ('model' '{' model+=Model ("," model+=Model)* '}')? ('modelrole' '{'
	//	modelrole+=ModelRole ("," modelrole+=ModelRole)* '}')?
	//	'}';
	public MODAElements getMODAAccess() {
		return pMODA;
	}
	
	public ParserRule getMODARule() {
		return getMODAAccess().getRule();
	}
	
	//ModelRole:
	//	DescriptiveModel | PredictiveModel | PrescriptiveModel;
	public ModelRoleElements getModelRoleAccess() {
		return pModelRole;
	}
	
	public ParserRule getModelRoleRule() {
		return getModelRoleAccess().getRule();
	}
	
	//SocioTechnicalSystem:
	//	{SocioTechnicalSystem}
	//	'SocioTechnicalSystem'
	//	name=EString
	//	'{' ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('prescriptivemodel'
	//	prescriptivemodel=[PrescriptiveModel|EString])?
	//	'}';
	public SocioTechnicalSystemElements getSocioTechnicalSystemAccess() {
		return pSocioTechnicalSystem;
	}
	
	public ParserRule getSocioTechnicalSystemRule() {
		return getSocioTechnicalSystemAccess().getRule();
	}
	
	//Data:
	//	{Data}
	//	'Data'
	//	name=EString
	//	'{' ('dataType' dataType=DataTypes)? ('software' software=[Software|EString])? ('sociotechnicalsystem'
	//	sociotechnicalsystem=[SocioTechnicalSystem|EString])? ('modelrole' modelrole=[ModelRole|EString])?
	//	'}';
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}
	
	//Software:
	//	{Software}
	//	'Software'
	//	name=EString
	//	'{' ('state' state=EString)? ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('prescriptivemodel'
	//	prescriptivemodel=[PrescriptiveModel|EString])?
	//	'}';
	public SoftwareElements getSoftwareAccess() {
		return pSoftware;
	}
	
	public ParserRule getSoftwareRule() {
		return getSoftwareAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Model:
	//	{Model}
	//	'Model'
	//	name=EString
	//	'{' ('modelrole' '(' modelrole+=[ModelRole|EString] ("," modelrole+=[ModelRole|EString])* ')')?
	//	'}';
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//PrescriptiveModel:
	//	'PrescriptiveModel'
	//	name=EString
	//	'{'
	//	'model' model=[Model|EString] ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('software'
	//	software=[Software|EString])? ('sociotechnicalsystem' sociotechnicalsystem=[SocioTechnicalSystem|EString])?
	//	('predictivemodel' predictivemodel=[PredictiveModel|EString])? ('prescriptivemodel'
	//	prescriptivemodel=[PrescriptiveModel|EString])? ('prescriptivemodeleOpposite'
	//	prescriptivemodeleOpposite=[PrescriptiveModel|EString])?
	//	'}';
	public PrescriptiveModelElements getPrescriptiveModelAccess() {
		return pPrescriptiveModel;
	}
	
	public ParserRule getPrescriptiveModelRule() {
		return getPrescriptiveModelAccess().getRule();
	}
	
	//PredictiveModel:
	//	'PredictiveModel'
	//	name=EString
	//	'{'
	//	'model' model=[Model|EString] ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('prescriptivemodel'
	//	prescriptivemodel=[PrescriptiveModel|EString])? ('descriptivemodel' descriptivemodel=[DescriptiveModel|EString])?
	//	'}';
	public PredictiveModelElements getPredictiveModelAccess() {
		return pPredictiveModel;
	}
	
	public ParserRule getPredictiveModelRule() {
		return getPredictiveModelAccess().getRule();
	}
	
	//DescriptiveModel:
	//	'DescriptiveModel'
	//	name=EString
	//	'{'
	//	'model' model=[Model|EString] ('data' '(' data+=[Data|EString] ("," data+=[Data|EString])* ')')? ('predictivemodel'
	//	predictivemodel=[PredictiveModel|EString])?
	//	'}';
	public DescriptiveModelElements getDescriptiveModelAccess() {
		return pDescriptiveModel;
	}
	
	public ParserRule getDescriptiveModelRule() {
		return getDescriptiveModelAccess().getRule();
	}
	
	//enum DataTypes:
	//	InputData | OutputData | ExternalData | MeasuredData;
	public DataTypesElements getDataTypesAccess() {
		return eDataTypes;
	}
	
	public EnumRule getDataTypesRule() {
		return getDataTypesAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
