/*
 * generated by Xtext 2.14.0
 */
package internship.fig1.ide

import com.google.inject.Guice
import internship.fig1.ModaRuntimeModule
import internship.fig1.ModaStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ModaIdeSetup extends ModaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ModaRuntimeModule, new ModaIdeModule))
	}
	
}
