/**
 * generated by Xtext 2.14.0
 */
package internship.fig1.validation;

import internship.fig1.validation.AbstractModaValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ModaValidator extends AbstractModaValidator {
}
