<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fig1" nsURI="http://www.irisa.fr/MODA/fig1" nsPrefix="fig1">
  <eClassifiers xsi:type="ecore:EClass" name="MODA" eSuperTypes="#//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sociotechnicalsystem" eType="#//SocioTechnicalSystem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" upperBound="-1"
        eType="#//Model" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelrole" upperBound="-1"
        eType="#//ModelRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="#//DataTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelrole" eType="#//ModelRole"
        eOpposite="#//ModelRole/data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherinterplay" upperBound="-1"
        eType="#//OtherInterplay" eOpposite="#//OtherInterplay/data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processing" eType="#//Processing"
        eOpposite="#//Processing/data"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRole" abstract="true" eSuperTypes="#//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="#//Model"
        eOpposite="#//Model/modelrole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"
        eOpposite="#//Data/modelrole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptiveModel" eSuperTypes="#//ModelRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preparation" eType="#//Preparation"
        eOpposite="#//Preparation/descriptivemodel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredictiveModel" eSuperTypes="#//ModelRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preparation" eType="#//Preparation"
        eOpposite="#//Preparation/predictivemodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analysis" eType="#//Analysis"
        eOpposite="#//Analysis/predictivemodel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrescriptiveModel" eSuperTypes="#//ModelRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enactment" eType="#//Enactment"
        eOpposite="#//Enactment/prescriptivemodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runningSoftware" eType="#//Deployment"
        eOpposite="#//Deployment/prescriptivemodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analysis" eType="#//Analysis"
        eOpposite="#//Analysis/prescriptivemodel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generation" eType="#//Generation"
        eOpposite="#//Generation/prescriptivemodel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Software" eSuperTypes="#//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processing" upperBound="-1"
        eType="#//Processing" eOpposite="#//Processing/software"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedModel" eType="#//Deployment"
        eOpposite="#//Deployment/software"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SocioTechnicalSystem" eSuperTypes="#//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="software" eType="#//Software"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherinterplay" eType="#//OtherInterplay"
        eOpposite="#//OtherInterplay/sociotechnicalsystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enactment" eType="#//Enactment"
        eOpposite="#//Enactment/sociotechnicalsystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataTypes">
    <eLiterals name="InputData"/>
    <eLiterals name="OutputData" value="1"/>
    <eLiterals name="ExternalData" value="2"/>
    <eLiterals name="MeasuredData" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//AbstractElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelrole" upperBound="-1"
        eType="#//ModelRole" eOpposite="#//ModelRole/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRelation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OtherInterplay" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" upperBound="-1"
        eType="#//Data" eOpposite="#//Data/otherinterplay"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sociotechnicalsystem" lowerBound="1"
        eType="#//SocioTechnicalSystem" eOpposite="#//SocioTechnicalSystem/otherinterplay"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Processing" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" upperBound="-1"
        eType="#//Data" eOpposite="#//Data/processing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="software" lowerBound="1"
        eType="#//Software" eOpposite="#//Software/processing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enactment" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prescriptivemodel" lowerBound="1"
        eType="#//PrescriptiveModel" eOpposite="#//PrescriptiveModel/enactment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sociotechnicalsystem" lowerBound="1"
        eType="#//SocioTechnicalSystem" eOpposite="#//SocioTechnicalSystem/enactment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deployment" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="software" lowerBound="1"
        eType="#//Software" eOpposite="#//Software/deployedModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prescriptivemodel" lowerBound="1"
        eType="#//PrescriptiveModel" eOpposite="#//PrescriptiveModel/runningSoftware"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preparation" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptivemodel" lowerBound="1"
        eType="#//DescriptiveModel" eOpposite="#//DescriptiveModel/preparation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predictivemodel" lowerBound="1"
        eType="#//PredictiveModel" eOpposite="#//PredictiveModel/preparation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Analysis" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predictivemodel" lowerBound="1"
        eType="#//PredictiveModel" eOpposite="#//PredictiveModel/analysis"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prescriptivemodel" lowerBound="1"
        eType="#//PrescriptiveModel" eOpposite="#//PrescriptiveModel/analysis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generation" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prescriptivemodel" lowerBound="2"
        upperBound="2" eType="#//PrescriptiveModel" eOpposite="#//PrescriptiveModel/generation"/>
  </eClassifiers>
</ecore:EPackage>
