<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fig1" nsURI="http://www.irisa.fr/MODA/fig1" nsPrefix="fig1">
  <eClassifiers xsi:type="ecore:EClass" name="MODA" eSuperTypes="#//ModaNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sociotechnicalsystem" eType="#//SocioTechnicalSystem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" upperBound="-1"
        eType="#//Model" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelrole" upperBound="-1"
        eType="#//ModelRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//ModaRelation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//ModaNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherinterplay" upperBound="-1"
        eType="#//OtherInterplay" eOpposite="#//OtherInterplay/data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datapurpose" upperBound="-1"
        eType="#//DataPurpose" eOpposite="#//DataPurpose/data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generalization" eType="#//Generalization"
        eOpposite="#//Generalization/source"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measuredData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRole" abstract="true" eSuperTypes="#//ModaNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Model"
        eOpposite="#//Model/modelrole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptiveModel" eSuperTypes="#//ModelRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingGeneralization"
        eType="#//Generalization" eOpposite="#//Generalization/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredictiveModel" eSuperTypes="#//ModelRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingPreparation" eType="#//Preparation"
        eOpposite="#//Preparation/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrescriptiveModel" eSuperTypes="#//ModelRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingEnactment" eType="#//Enactment"
        eOpposite="#//Enactment/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingDeployment" eType="#//Deployment"
        eOpposite="#//Deployment/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingAnalysis" eType="#//Analysis"
        eOpposite="#//Analysis/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingGeneration" eType="#//Generation"
        eOpposite="#//Generation/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingGeneration" eType="#//Generation"
        eOpposite="#//Generation/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Software" eSuperTypes="#//ModaNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processing" upperBound="-1"
        eType="#//DataPurpose" eOpposite="#//DataPurpose/software"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingDeployment" eType="#//Deployment"
        eOpposite="#//Deployment/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SocioTechnicalSystem" eSuperTypes="#//ModaNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="software" eType="#//Software"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="otherinterplay" eType="#//OtherInterplay"
        eOpposite="#//OtherInterplay/sociotechnicalsystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingEnactment" eType="#//Enactment"
        eOpposite="#//Enactment/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataKind">
    <eLiterals name="InputData"/>
    <eLiterals name="OutputData" value="1"/>
    <eLiterals name="ExternalData" value="2"/>
    <eLiterals name="MeasuredData" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//ModaNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelrole" upperBound="-1"
        eType="#//ModelRole" eOpposite="#//ModelRole/model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModaNode" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingAnalysis" eType="#//Analysis"
        eOpposite="#//Analysis/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingPreparation" eType="#//Preparation"
        eOpposite="#//Preparation/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModaRelation" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="OtherInterplay" eSuperTypes="#//ModaRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" lowerBound="1" upperBound="-1"
        eType="#//Data" eOpposite="#//Data/otherinterplay"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sociotechnicalsystem" eType="#//SocioTechnicalSystem"
        eOpposite="#//SocioTechnicalSystem/otherinterplay"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPurpose" eSuperTypes="#//ModaRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" eType="#//Data" eOpposite="#//Data/datapurpose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="software" eType="#//Software"
        eOpposite="#//Software/processing"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataKind" eType="#//DataKind"
        defaultValueLiteral="InputData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enactment" eSuperTypes="#//ModaRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//PrescriptiveModel"
        eOpposite="#//PrescriptiveModel/outgoingEnactment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//SocioTechnicalSystem"
        eOpposite="#//SocioTechnicalSystem/incomingEnactment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deployment" eSuperTypes="#//ModaRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Software"
        eOpposite="#//Software/incomingDeployment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//PrescriptiveModel"
        eOpposite="#//PrescriptiveModel/outgoingDeployment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preparation" eSuperTypes="#//ModaRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//PredictiveModel"
        eOpposite="#//PredictiveModel/incomingPreparation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ModaNode"
        eOpposite="#//ModaNode/outgoingPreparation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Analysis" eSuperTypes="#//ModaRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//PrescriptiveModel"
        eOpposite="#//PrescriptiveModel/incomingAnalysis"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ModaNode"
        eOpposite="#//ModaNode/outgoingAnalysis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generation" eSuperTypes="#//ModaRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//PrescriptiveModel"
        eOpposite="#//PrescriptiveModel/outgoingGeneration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//PrescriptiveModel"
        eOpposite="#//PrescriptiveModel/incomingGeneration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//ModaRelation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" upperBound="-1"
        eType="#//Data" eOpposite="#//Data/generalization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//DescriptiveModel"
        eOpposite="#//DescriptiveModel/incomingGeneralization"/>
  </eClassifiers>
</ecore:EPackage>
