/*
 * generated by Xtext 2.14.0
 */
package internship


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModaStandaloneSetup extends ModaStandaloneSetupGenerated {

	def static void doSetup() {
		new ModaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
