/**
 * generated by Xtext 2.14.0
 */
package internship.fig1.ide;

import internship.fig1.ide.AbstractModaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ModaIdeModule extends AbstractModaIdeModule {
}
