/**
 * generated by Xtext 2.14.0
 */
package internship.fig1.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import internship.fig1.ModaRuntimeModule;
import internship.fig1.ModaStandaloneSetup;
import internship.fig1.ide.ModaIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ModaIdeSetup extends ModaStandaloneSetup {
  @Override
  public Injector createInjector() {
    ModaRuntimeModule _modaRuntimeModule = new ModaRuntimeModule();
    ModaIdeModule _modaIdeModule = new ModaIdeModule();
    return Guice.createInjector(Modules2.mixin(_modaRuntimeModule, _modaIdeModule));
  }
}
