/*
 * generated by Xtext 2.14.0
 */
package internship.parser.antlr;

import com.google.inject.Inject;
import internship.parser.antlr.internal.InternalModaParser;
import internship.services.ModaGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ModaParser extends AbstractAntlrParser {

	@Inject
	private ModaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalModaParser createParser(XtextTokenStream stream) {
		return new InternalModaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MODA";
	}

	public ModaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ModaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
