/*
 * generated by Xtext 2.14.0
 */
package internship.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractModaScopeProvider extends DelegatingScopeProvider {
}
