/**
 * generated by Xtext 2.14.0
 */
package internship.fig1;

import internship.fig1.ModaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModaStandaloneSetup extends ModaStandaloneSetupGenerated {
  public static void doSetup() {
    new ModaStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
