/**
 * generated by Xtext 2.14.0
 */
package internship.fig1;

import internship.fig1.AbstractModaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModaRuntimeModule extends AbstractModaRuntimeModule {
}
