/**
 * generated by Xtext 2.14.0
 */
package internship.fig1.scoping;

import internship.fig1.scoping.AbstractModaScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ModaScopeProvider extends AbstractModaScopeProvider {
}
