/**
 * generated by Xtext 2.14.0
 */
package internship.fig1.formatting2;

import com.google.inject.Inject;
import internship.fig1.services.ModaGrammarAccess;
import internship.moda.fig1.Data;
import internship.moda.fig1.MODA;
import internship.moda.fig1.Model;
import internship.moda.fig1.ModelRole;
import internship.moda.fig1.SocioTechnicalSystem;
import internship.moda.fig1.Software;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class ModaFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ModaGrammarAccess _modaGrammarAccess;
  
  protected void _format(final MODA mODA, @Extension final IFormattableDocument document) {
    document.<SocioTechnicalSystem>format(mODA.getSociotechnicalsystem());
    EList<Data> _data = mODA.getData();
    for (final Data data : _data) {
      document.<Data>format(data);
    }
    document.<Software>format(mODA.getSoftware());
    EList<Model> _model = mODA.getModel();
    for (final Model model : _model) {
      document.<Model>format(model);
    }
    EList<ModelRole> _modelrole = mODA.getModelrole();
    for (final ModelRole modelRole : _modelrole) {
      document.<ModelRole>format(modelRole);
    }
  }
  
  public void format(final Object mODA, final IFormattableDocument document) {
    if (mODA instanceof XtextResource) {
      _format((XtextResource)mODA, document);
      return;
    } else if (mODA instanceof MODA) {
      _format((MODA)mODA, document);
      return;
    } else if (mODA instanceof EObject) {
      _format((EObject)mODA, document);
      return;
    } else if (mODA == null) {
      _format((Void)null, document);
      return;
    } else if (mODA != null) {
      _format(mODA, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(mODA, document).toString());
    }
  }
}
