/*
 * generated by Xtext 2.14.0
 */
package internship.fig1.ui.tests;

import com.google.inject.Injector;
import internship.MODA.fig1.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ModaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("internship.fig1.Moda");
	}

}
