/*
 * generated by Xtext 2.14.0
 */
package internship.fig1.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import internship.fig1.ide.contentassist.antlr.internal.InternalModaParser;
import internship.fig1.services.ModaGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ModaParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ModaGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ModaGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelRoleAccess().getAlternatives(), "rule__ModelRole__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getDataTypesAccess().getAlternatives(), "rule__DataTypes__Alternatives");
			builder.put(grammarAccess.getMODAAccess().getGroup(), "rule__MODA__Group__0");
			builder.put(grammarAccess.getMODAAccess().getGroup_4(), "rule__MODA__Group_4__0");
			builder.put(grammarAccess.getMODAAccess().getGroup_5(), "rule__MODA__Group_5__0");
			builder.put(grammarAccess.getMODAAccess().getGroup_5_3(), "rule__MODA__Group_5_3__0");
			builder.put(grammarAccess.getMODAAccess().getGroup_6(), "rule__MODA__Group_6__0");
			builder.put(grammarAccess.getMODAAccess().getGroup_7(), "rule__MODA__Group_7__0");
			builder.put(grammarAccess.getMODAAccess().getGroup_7_3(), "rule__MODA__Group_7_3__0");
			builder.put(grammarAccess.getMODAAccess().getGroup_8(), "rule__MODA__Group_8__0");
			builder.put(grammarAccess.getMODAAccess().getGroup_8_3(), "rule__MODA__Group_8_3__0");
			builder.put(grammarAccess.getSocioTechnicalSystemAccess().getGroup(), "rule__SocioTechnicalSystem__Group__0");
			builder.put(grammarAccess.getSocioTechnicalSystemAccess().getGroup_4(), "rule__SocioTechnicalSystem__Group_4__0");
			builder.put(grammarAccess.getSocioTechnicalSystemAccess().getGroup_4_3(), "rule__SocioTechnicalSystem__Group_4_3__0");
			builder.put(grammarAccess.getSocioTechnicalSystemAccess().getGroup_5(), "rule__SocioTechnicalSystem__Group_5__0");
			builder.put(grammarAccess.getDataAccess().getGroup(), "rule__Data__Group__0");
			builder.put(grammarAccess.getDataAccess().getGroup_4(), "rule__Data__Group_4__0");
			builder.put(grammarAccess.getDataAccess().getGroup_5(), "rule__Data__Group_5__0");
			builder.put(grammarAccess.getDataAccess().getGroup_6(), "rule__Data__Group_6__0");
			builder.put(grammarAccess.getDataAccess().getGroup_7(), "rule__Data__Group_7__0");
			builder.put(grammarAccess.getSoftwareAccess().getGroup(), "rule__Software__Group__0");
			builder.put(grammarAccess.getSoftwareAccess().getGroup_4(), "rule__Software__Group_4__0");
			builder.put(grammarAccess.getSoftwareAccess().getGroup_5(), "rule__Software__Group_5__0");
			builder.put(grammarAccess.getSoftwareAccess().getGroup_5_3(), "rule__Software__Group_5_3__0");
			builder.put(grammarAccess.getSoftwareAccess().getGroup_6(), "rule__Software__Group_6__0");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_4(), "rule__Model__Group_4__0");
			builder.put(grammarAccess.getModelAccess().getGroup_4_3(), "rule__Model__Group_4_3__0");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getGroup(), "rule__PrescriptiveModel__Group__0");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getGroup_5(), "rule__PrescriptiveModel__Group_5__0");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getGroup_5_3(), "rule__PrescriptiveModel__Group_5_3__0");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getGroup_6(), "rule__PrescriptiveModel__Group_6__0");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getGroup_7(), "rule__PrescriptiveModel__Group_7__0");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getGroup_8(), "rule__PrescriptiveModel__Group_8__0");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getGroup_9(), "rule__PrescriptiveModel__Group_9__0");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getGroup_10(), "rule__PrescriptiveModel__Group_10__0");
			builder.put(grammarAccess.getPredictiveModelAccess().getGroup(), "rule__PredictiveModel__Group__0");
			builder.put(grammarAccess.getPredictiveModelAccess().getGroup_5(), "rule__PredictiveModel__Group_5__0");
			builder.put(grammarAccess.getPredictiveModelAccess().getGroup_5_3(), "rule__PredictiveModel__Group_5_3__0");
			builder.put(grammarAccess.getPredictiveModelAccess().getGroup_6(), "rule__PredictiveModel__Group_6__0");
			builder.put(grammarAccess.getPredictiveModelAccess().getGroup_7(), "rule__PredictiveModel__Group_7__0");
			builder.put(grammarAccess.getDescriptiveModelAccess().getGroup(), "rule__DescriptiveModel__Group__0");
			builder.put(grammarAccess.getDescriptiveModelAccess().getGroup_5(), "rule__DescriptiveModel__Group_5__0");
			builder.put(grammarAccess.getDescriptiveModelAccess().getGroup_5_3(), "rule__DescriptiveModel__Group_5_3__0");
			builder.put(grammarAccess.getDescriptiveModelAccess().getGroup_6(), "rule__DescriptiveModel__Group_6__0");
			builder.put(grammarAccess.getMODAAccess().getNameAssignment_2(), "rule__MODA__NameAssignment_2");
			builder.put(grammarAccess.getMODAAccess().getSociotechnicalsystemAssignment_4_1(), "rule__MODA__SociotechnicalsystemAssignment_4_1");
			builder.put(grammarAccess.getMODAAccess().getDataAssignment_5_2(), "rule__MODA__DataAssignment_5_2");
			builder.put(grammarAccess.getMODAAccess().getDataAssignment_5_3_1(), "rule__MODA__DataAssignment_5_3_1");
			builder.put(grammarAccess.getMODAAccess().getSoftwareAssignment_6_1(), "rule__MODA__SoftwareAssignment_6_1");
			builder.put(grammarAccess.getMODAAccess().getModelAssignment_7_2(), "rule__MODA__ModelAssignment_7_2");
			builder.put(grammarAccess.getMODAAccess().getModelAssignment_7_3_1(), "rule__MODA__ModelAssignment_7_3_1");
			builder.put(grammarAccess.getMODAAccess().getModelroleAssignment_8_2(), "rule__MODA__ModelroleAssignment_8_2");
			builder.put(grammarAccess.getMODAAccess().getModelroleAssignment_8_3_1(), "rule__MODA__ModelroleAssignment_8_3_1");
			builder.put(grammarAccess.getSocioTechnicalSystemAccess().getNameAssignment_2(), "rule__SocioTechnicalSystem__NameAssignment_2");
			builder.put(grammarAccess.getSocioTechnicalSystemAccess().getDataAssignment_4_2(), "rule__SocioTechnicalSystem__DataAssignment_4_2");
			builder.put(grammarAccess.getSocioTechnicalSystemAccess().getDataAssignment_4_3_1(), "rule__SocioTechnicalSystem__DataAssignment_4_3_1");
			builder.put(grammarAccess.getSocioTechnicalSystemAccess().getPrescriptivemodelAssignment_5_1(), "rule__SocioTechnicalSystem__PrescriptivemodelAssignment_5_1");
			builder.put(grammarAccess.getDataAccess().getNameAssignment_2(), "rule__Data__NameAssignment_2");
			builder.put(grammarAccess.getDataAccess().getDataTypeAssignment_4_1(), "rule__Data__DataTypeAssignment_4_1");
			builder.put(grammarAccess.getDataAccess().getSoftwareAssignment_5_1(), "rule__Data__SoftwareAssignment_5_1");
			builder.put(grammarAccess.getDataAccess().getSociotechnicalsystemAssignment_6_1(), "rule__Data__SociotechnicalsystemAssignment_6_1");
			builder.put(grammarAccess.getDataAccess().getModelroleAssignment_7_1(), "rule__Data__ModelroleAssignment_7_1");
			builder.put(grammarAccess.getSoftwareAccess().getNameAssignment_2(), "rule__Software__NameAssignment_2");
			builder.put(grammarAccess.getSoftwareAccess().getStateAssignment_4_1(), "rule__Software__StateAssignment_4_1");
			builder.put(grammarAccess.getSoftwareAccess().getDataAssignment_5_2(), "rule__Software__DataAssignment_5_2");
			builder.put(grammarAccess.getSoftwareAccess().getDataAssignment_5_3_1(), "rule__Software__DataAssignment_5_3_1");
			builder.put(grammarAccess.getSoftwareAccess().getPrescriptivemodelAssignment_6_1(), "rule__Software__PrescriptivemodelAssignment_6_1");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_2(), "rule__Model__NameAssignment_2");
			builder.put(grammarAccess.getModelAccess().getModelroleAssignment_4_2(), "rule__Model__ModelroleAssignment_4_2");
			builder.put(grammarAccess.getModelAccess().getModelroleAssignment_4_3_1(), "rule__Model__ModelroleAssignment_4_3_1");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getNameAssignment_1(), "rule__PrescriptiveModel__NameAssignment_1");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getModelAssignment_4(), "rule__PrescriptiveModel__ModelAssignment_4");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getDataAssignment_5_2(), "rule__PrescriptiveModel__DataAssignment_5_2");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getDataAssignment_5_3_1(), "rule__PrescriptiveModel__DataAssignment_5_3_1");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getSoftwareAssignment_6_1(), "rule__PrescriptiveModel__SoftwareAssignment_6_1");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getSociotechnicalsystemAssignment_7_1(), "rule__PrescriptiveModel__SociotechnicalsystemAssignment_7_1");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getPredictivemodelAssignment_8_1(), "rule__PrescriptiveModel__PredictivemodelAssignment_8_1");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getPrescriptivemodelAssignment_9_1(), "rule__PrescriptiveModel__PrescriptivemodelAssignment_9_1");
			builder.put(grammarAccess.getPrescriptiveModelAccess().getPrescriptivemodeleOppositeAssignment_10_1(), "rule__PrescriptiveModel__PrescriptivemodeleOppositeAssignment_10_1");
			builder.put(grammarAccess.getPredictiveModelAccess().getNameAssignment_1(), "rule__PredictiveModel__NameAssignment_1");
			builder.put(grammarAccess.getPredictiveModelAccess().getModelAssignment_4(), "rule__PredictiveModel__ModelAssignment_4");
			builder.put(grammarAccess.getPredictiveModelAccess().getDataAssignment_5_2(), "rule__PredictiveModel__DataAssignment_5_2");
			builder.put(grammarAccess.getPredictiveModelAccess().getDataAssignment_5_3_1(), "rule__PredictiveModel__DataAssignment_5_3_1");
			builder.put(grammarAccess.getPredictiveModelAccess().getPrescriptivemodelAssignment_6_1(), "rule__PredictiveModel__PrescriptivemodelAssignment_6_1");
			builder.put(grammarAccess.getPredictiveModelAccess().getDescriptivemodelAssignment_7_1(), "rule__PredictiveModel__DescriptivemodelAssignment_7_1");
			builder.put(grammarAccess.getDescriptiveModelAccess().getNameAssignment_1(), "rule__DescriptiveModel__NameAssignment_1");
			builder.put(grammarAccess.getDescriptiveModelAccess().getModelAssignment_4(), "rule__DescriptiveModel__ModelAssignment_4");
			builder.put(grammarAccess.getDescriptiveModelAccess().getDataAssignment_5_2(), "rule__DescriptiveModel__DataAssignment_5_2");
			builder.put(grammarAccess.getDescriptiveModelAccess().getDataAssignment_5_3_1(), "rule__DescriptiveModel__DataAssignment_5_3_1");
			builder.put(grammarAccess.getDescriptiveModelAccess().getPredictivemodelAssignment_6_1(), "rule__DescriptiveModel__PredictivemodelAssignment_6_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ModaGrammarAccess grammarAccess;

	@Override
	protected InternalModaParser createParser() {
		InternalModaParser result = new InternalModaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ModaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ModaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
